import com.google.gson.Gson
import org.junit.Test
import org.junit.jupiter.api.assertThrows
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull

class ClientServiceTest {

    private val gson = Gson()
    private val clientService = ClientService()

    @Test
    fun `success save client`() {
        val client = getClientFromJson("/success/user.json")
        val result = clientService.saveClient(client)
        assertNotNull(result)
    }

    @Test
    fun `fail save client - fio validation errors`() {
        val client = getClientFromJson("/fail/user_with_bad_fio.json")
        val exception = assertFailsWith<ValidationException>("Ожидаемая ошибка") {
            clientService.saveClient(client)
        }
        assertEquals(exception.errorCode[0], ErrorCode.INVALID_LENGTH)
        assertEquals(exception.errorCode[1], ErrorCode.INVALID_LANGUAGE)
    }

    @Test
    fun `fail save client - phone validation errors`() {
        val client = getClientFromJson("/fail/user_with_bad_phone.json")
        val exception = assertFailsWith<ValidationException>("Ожидаемая ошибка") {
            clientService.saveClient(client)
        }
        assertEquals(exception.errorCode[0], ErrorCode.INVALID_PHONE)
    }

    @Test
    fun `fail save client - mail validation errors`() {
        val client = getClientFromJson("/fail/user_with_bad_mail.json")
        val exception = assertFailsWith<ValidationException>("Ожидаемая ошибка") {
            clientService.saveClient(client)
        }
        assertEquals(exception.errorCode[0], ErrorCode.INVALID_MAIL)
    }

    @Test
    fun `fail save client - snils check validation errors`() {
        val client = getClientFromJson("/fail/user_with_bad_snils_check.json")
        val exception = assertFailsWith<ValidationException>("Ожидаемая ошибка") {
            clientService.saveClient(client)
        }
        assertEquals(exception.errorCode[0], ErrorCode.INVALID_CHECK_SNILS)
    }

    @Test
    fun `fail save client - validation errors`() {
        val client = getClientFromJson("/fail/user_data_corrupted.json")
        val exception = assertFailsWith<ValidationException>("Ожидаемая ошибка") {
            clientService.saveClient(client)
        }
        assertEquals(exception.errorCode[0], ErrorCode.INVALID_ZERO)
        assertEquals(exception.errorCode[1], ErrorCode.INVALID_LENGTH)
        assertEquals(exception.errorCode[2], ErrorCode.INVALID_LENGTH)
        assertEquals(exception.errorCode[3], ErrorCode.INVALID_MAIL)
        assertEquals(exception.errorCode[4], ErrorCode.INVALID_CHECK_SNILS)

    }

    private fun getClientFromJson(fileName: String): Client = this::class.java.getResource(fileName)
        .takeIf { it != null }
        ?.let { gson.fromJson(it.readText(), Client::class.java) }
        ?: throw Exception("Что-то пошло не так))")
}
